# Generated by Django 2.2.24 on 2022-07-10 20:21

from django.db import migrations


def set_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gt=2015).update(new_building=True)
    Flat.objects.filter(construction_year=2015).update(new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20220710_1459'),
    ]

    operations = [
        migrations.RunPython(set_new_buildings)
    ]


