# Generated by Django 2.2.24 on 2022-07-11 15:32

import phonenumbers
from django.db import migrations


def normalise_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    for flat in flats:
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parsed_number):
            pure_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = pure_number
            flat.save(update_fields=["owner_pure_phone"])
        else:
            flat.owner_pure_phone = None
            flat.save(update_fields=["owner_pure_phone"])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalise_numbers),
    ]
