# Generated by Django 2.2.24 on 2022-07-26 19:17

from django.db import migrations


def copy_flat_owners_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(name=flat.owner, number=flat.owners_phonenumber, pure_number=flat.owner_pure_phone)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20220726_2216'),
    ]

    operations = [
        migrations.RunPython(copy_flat_owners_to_owners),
    ]
