# Generated by Django 2.2.24 on 2022-07-26 19:53

from django.db import migrations


def connect_flats_to_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    owners = Owner.objects.all()
    for owner in owners:
        flats = Flat.objects.filter(owner=owner.name, owners_phonenumber=owner.number)
        owner.flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220726_2248'),
    ]

    operations = [
        migrations.RunPython(connect_flats_to_owners),
    ]
